import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { GameProvider } from "./context/GameLogic";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const AvantGarde = localFont({
  src: [
    {
      path: "../public/AvantGardeMedium.otf",
      weight: "400",
    },
    {
      path: "../public/AvantGardeDemi.otf",
      weight: "700",
    },
  ],
  variable: "--font-avant-garde",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${AvantGarde.variable}`}>
        <GameProvider>{children}</GameProvider>
      </body>
    </html>
  );
}
